/*
 * Copyright 2023 Autoware Foundation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Authors: Mingyu Li
 *
 */

#ifndef TRAFFIC_LIGHT_OCCLUSION_PREDICTOR__NODE_HPP_
#define TRAFFIC_LIGHT_OCCLUSION_PREDICTOR__NODE_HPP_


#include <rclcpp/rclcpp.hpp>
#include <autoware_auto_perception_msgs/msg/traffic_light_roi_array.hpp>
#include <autoware_auto_perception_msgs/msg/predicted_objects.hpp>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include <sensor_msgs/msg/camera_info.hpp>
#include <sensor_msgs/msg/point_cloud2.hpp>
#include <image_geometry/pinhole_camera_model.h>
#include <tf2_ros/buffer.h>
#include <tf2_ros/transform_listener.h>
#include <traffic_light_occlusion_predictor/occlusion_predictor.hpp>
#include <message_filters/subscriber.h>
#include <message_filters/synchronizer.h>
#include <message_filters/time_synchronizer.h>
#include <mutex>


namespace traffic_light
{
class TrafficLightOcclusionPredictorNodelet : public rclcpp::Node
{
public:
  explicit TrafficLightOcclusionPredictorNodelet(const rclcpp::NodeOptions & node_options);

private:
  struct Config
  {
    double azimuth_occlusion_resolution;
    double elevation_occlusion_resolution;
    int min_cloud_size;
    bool enable_point_cloud_compensation;
  };
private:
  /**
   * @brief receive camera_info and rough rois generated by traffic_light_map_based_detector,
   * calculate the occlusion probability of each rough roi and publish.
   * 
   * @param in_image_msg 
   * @param in_roi_msg 
   */
  void callback(
    const sensor_msgs::msg::CameraInfo::ConstSharedPtr in_image_msg,
    const autoware_auto_perception_msgs::msg::TrafficLightRoiArray::ConstSharedPtr in_roi_msg
  );
  /**
   * @brief receive the point cloud for calculating the occlusion
   * 
   * @param msg 
   */
  void pointCloudCallback(const sensor_msgs::msg::PointCloud2::ConstSharedPtr msg);
  /**
   * @brief receive dynamic objects for compensating the point cloud
   * 
   * @param msg 
   */
  void perceptionObjectsCallback(
    const autoware_auto_perception_msgs::msg::PredictedObjects::ConstSharedPtr msg);
  /**
   * @brief subscribers
   * 
   */
  typedef message_filters::sync_policies::ExactTime<
    sensor_msgs::msg::CameraInfo, autoware_auto_perception_msgs::msg::TrafficLightRoiArray>
    SyncPolicy;
  typedef message_filters::Synchronizer<SyncPolicy> Sync;
  std::shared_ptr<Sync> sync_;
  message_filters::Subscriber<sensor_msgs::msg::CameraInfo> camera_info_sub_;
  message_filters::Subscriber<autoware_auto_perception_msgs::msg::TrafficLightRoiArray> roi_sub_;
  rclcpp::Subscription<sensor_msgs::msg::PointCloud2>::SharedPtr point_cloud_sub_;  
  rclcpp::Subscription<autoware_auto_perception_msgs::msg::PredictedObjects>::SharedPtr objects_sub_;
  /**
   * @brief publishers
   * 
   */
  rclcpp::Publisher<autoware_auto_perception_msgs::msg::TrafficLightRoiArray>::SharedPtr roi_pub_;
  rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr debug_cloud_pub_;

  tf2_ros::Buffer tf_buffer_;
  tf2_ros::TransformListener tf_listener_;
  Config config_;
  /**
   * @brief main class for calculating the occlusion probability
   * 
   */
  CloudOcclusionPredictor cloud_occlusion_predictor_;
};
}  // namespace traffic_light
#endif  // TRAFFIC_LIGHT_OCCLUSION_PREDICTOR__NODE_HPP_
